testConfig: firstTest

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://49.235.118.56:3306/fp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.fp.eureka-hello.model
  type-handlers-package: com.fp.eureka-hello.handler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30